name: Selenium Test Workflow

on: push

jobs: 
  Selenium_Test_Job1:
  name: Selenium Test Job
    runs-on:ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      - run: echo "This is running inside a ${{ runner.os}} server in GitHub"
      
